version: '3.8'
services:
  flask:
    build: ./
    image: dictionary:latest
    container_name: terms
    restart: on-failure
    environment:
      - FLASK_APP=main.py
    volumes:
      - ./:/server
    ports:
      - "5000:5000"
    command: flask run